### PR TITLE
Fix build error on windows - remove constexpressed externs

### PR DESCRIPTION
**Pull request by mjwitte**
Pull request overview
---------------------
 - Fixes build error on win64 with VS2019 (version 16.8.6) introduced in #8623.
https://github.com/NREL/EnergyPlus/pull/8623/files#diff-20af84d22ee6caa88c302db1550d67422b6395a3f2674c6281ee17f4aede7986L109-R113

```
6>D:\MJWGit\EnergyPlus\src\EnergyPlus\HeatBalFiniteDiffManager.cc(109,22): error C2370: 'EnergyPlus::HeatBalFiniteDiffManager::Lambda': redefinition; different storage class
6>D:\MJWGit\EnergyPlus\src\EnergyPlus/HeatBalFiniteDiffManager.hh(70): message : see declaration of 'EnergyPlus::HeatBalFiniteDiffManager::Lambda'
6>D:\MJWGit\EnergyPlus\src\EnergyPlus\HeatBalFiniteDiffManager.cc(110,22): error C2370: 'EnergyPlus::HeatBalFiniteDiffManager::smalldiff': redefinition; different storage class
6>D:\MJWGit\EnergyPlus\src\EnergyPlus/HeatBalFiniteDiffManager.hh(71): message : see declaration of 'EnergyPlus::HeatBalFiniteDiffManager::smalldiff'
6>D:\MJWGit\EnergyPlus\src\EnergyPlus\HeatBalFiniteDiffManager.cc(112,19): error C2370: 'EnergyPlus::HeatBalFiniteDiffManager::CrankNicholsonSecondOrder': redefinition; different storage class
6>D:\MJWGit\EnergyPlus\src\EnergyPlus/HeatBalFiniteDiffManager.hh(73): message : see declaration of 'EnergyPlus::HeatBalFiniteDiffManager::CrankNicholsonSecondOrder'
6>D:\MJWGit\EnergyPlus\src\EnergyPlus\HeatBalFiniteDiffManager.cc(113,19): error C2370: 'EnergyPlus::HeatBalFiniteDiffManager::FullyImplicitFirstOrder': redefinition; different storage class
6>D:\MJWGit\EnergyPlus\src\EnergyPlus/HeatBalFiniteDiffManager.hh(74): message : see declaration of 'EnergyPlus::HeatBalFiniteDiffManager::FullyImplicitFirstOrder'
```

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

**Comment by mitchute** [comment]
Thanks for fixing this. I thought I was in a function when I deleted these, not right out in the namespace. Interesting that the build didn't fail on Mac or Linux.

**Comment by mjwitte** [comment]
Windows seems to be more fussy lately than the others. Anyways, easy fix.

**Comment by Myoldmopar** [comment]
Thanks for the hotfix @mjwitte !
