### PR TITLE
Fix VS2017 compile error

### PR DESCRIPTION
**Pull request by mjwitte**
Pull request overview
---------------------
Fixes compiler error with windows Visual Studio 2017.
```
\Develop\src\EnergyPlus\EvaporativeCoolers.cc(2804): error C2440: '<function-style-cast>': cannot convert from 'const T' to 'EnergyPlus::EvaporativeCoolers::OperatingMode'
        with
        [
            T=double
        ]
\Develop\src\EnergyPlus\EvaporativeCoolers.cc(2804): note: Conversions between enumeration and floating point values are no longer allowed  
```
Introduced in https://github.com/NREL/EnergyPlus/commit/9a2f824555804ae187d197dc69d3f2acc45e3ed1. VS2019 is fine with the current code.

### Pull Request Author
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [x] Label the PR with at least one of: Defect, Refactoring, NewFeature, Performance, and/or DoNoPublish
 - [ ] Pull requests that impact EnergyPlus code must also include unit tests to cover enhancement or defect repair
 - [ ] Author should provide a "walkthrough" of relevant code changes using a GitHub code review comment process
 - [ ] If any diffs are expected, author must demonstrate they are justified using plots and descriptions
 - [ ] If changes fix a defect, the fix should be demonstrated in plots and descriptions
 - [ ] If any defect files are updated to a more recent version, upload new versions here or on DevSupport
 - [ ] If IDD requires transition, transition source, rules, ExpandObjects, and IDFs must be updated, and add IDDChange label
 - [ ] If structural output changes, add to output rules file and add OutputChange label
 - [ ] If adding/removing any LaTeX docs or figures, update that document's CMakeLists file dependencies

### Reviewer
This will not be exhaustively relevant to every PR.
 - [ ] Perform a Code Review on GitHub
 - [ ] If branch is behind develop, merge develop and build locally to check for side effects of the merge
 - [ ] If defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If feature, test running new feature, try creative ways to break it
 - [ ] CI status: all green or justified
 - [ ] Check that performance is not impacted (CI Linux results include performance check)
 - [ ] Run Unit Test(s) locally
 - [ ] Check any new function arguments for performance impacts
 - [ ] Verify IDF naming conventions and styles, memos and notes and defaults
 - [ ] If new idf included, locally check the err file and other outputs

### CODE REVIEW

File: src/EnergyPlus/EvaporativeCoolers.cc [hunk 1]
```diff
@@ -2801,7 +2801,7 @@ namespace EvaporativeCoolers {
         auto &EvapCond(state.dataEvapCoolers->EvapCond);
 
         EvapCoolIndex = int(Par(1));
-        DryOrWetOperatingMode = OperatingMode(Par(2));
+        DryOrWetOperatingMode = OperatingMode(int(Par(2)));
```
Comment (Myoldmopar) [inline src/EnergyPlus/EvaporativeCoolers.cc:2804]: This is fine...for now.  We need a targeted overhaul of the root-finding methods in EnergyPlus at some point.  The ways we packaged up a payload of data was fine in Fortran, but there are much better ways in C++.  In any case, I didn't actually realize we could even compile in VS2017 anymore, so if this is all it takes to get it compiling again, then so be it.  Thanks for the fix.

**Review by Myoldmopar — APPROVED** [review]
