### PR TITLE
Fix intel compiler build error on linux

### LINKED ISSUE #4697: Build flags don't work when using Intel compiler on Linux
Hit this when building on Peregrine at NREL:

Scanning dependencies of target sqlite
[  1%] Building C object third_party/SQLite/CMakeFiles/sqlite.dir/sqlite3.c.o
icc: error #10236: File not found:  '/Qdiag-disable:1786,2259'
icc: error #10236: File not found:  '/DVC_EXTRALEAN'
icc: error #10236: File not found:  '/DWIN32_LEAN_AND_MEAN'
icc: error #10236: File not found:  '/DNOMINMAX'
icc: error #10236: File not found:  '/W0'
/home/dmacumbe/energyplus/third_party/SQLite/sqlite3.c(46945): warning #810: conversion from "char *" to "int" may lose significant bits
      if( (enc & SQLITE_UTF16_ALIGNED)!=0 && 1==(1&SQLITE_PTR_TO_INT(pVal->z)) ){

### PR DESCRIPTION
**Pull request by mbadams5**
Fixes #4697

@macumber Can you test and see if this resolves #4697 for you? It now compiles on my Ubuntu 14.04 with Intel compiler 15.

I also commented out three release flags for Intel compiler dealing with reduced floating point math precision for increased speed. The other compilers don't have these flags so I don't think it is appropriate for Intel to have them.

@Myoldmopar fyi

### CODE REVIEW

**Comment by Myoldmopar** [comment]
Thanks @mbadams5.  I will await @macumber or someone else to verify as I don't have Intel.

**Comment by macumber** [comment]
I'll get to this next week

**Comment by Myoldmopar** [comment]
@macumber Are you able to test this and verify it builds with Intel?

**Comment by macumber** [comment]
I'll take a look right now

**Comment by macumber** [comment]
Here is my version of the compiler:

```
[dmacumbe@insight4 build]$ icpc --version
```

   icpc (ICC) 13.1.3 20130607
   Copyright (C) 1985-2013 Intel Corporation.  All rights reserved.

I get the following error:

```
icpc: command line warning #10158: ignoring option '-diag-disable'; argument must be separate
/home/dmacumbe/energyplus/third_party/ObjexxFCL/src/ObjexxFCL/Cstring.hh(73): error: expected a ";"
Cstring( Cstring && s ) NOEXCEPT :
```

Looks like the problem is no support for NOEXCEPT:

https://software.intel.com/en-us/articles/c0x-features-supported-by-intel-c-compiler

**Comment by macumber** [comment]
Built with Intel icpc v15.0, just a few warnings about pragmas:

```
/home/dmacumbe/energyplus/third_party/ObjexxFCL/src/ObjexxFCL/Array4S.hh(3308):       warning #161: unrecognized #pragma
  #pragma clang diagnostic push
          ^
          detected during:
            instantiation of "ObjexxFCL::Array4S<T>::Array4S(T *, int64_t={long}      , const ObjexxFCL::Array4S<T>::DS &, const ObjexxFCL::Array4S<T>::DS &, const Ob      jexxFCL::Array4S<T>::DS &, const ObjexxFCL::Array4S<T>::DS &) [with T=double]" a      t line 1699 of "/home/dmacumbe/energyplus/third_party/ObjexxFCL/src/ObjexxFCL/Ar      ray5.hh"
            instantiation of "ObjexxFCL::Array4S<T> ObjexxFCL::Array5<T>::operat      or()(int, const ObjexxFCL::Array5<T>::IS &, const ObjexxFCL::Array5<T>::IS &, co      nst ObjexxFCL::Array5<T>::IS &, const ObjexxFCL::Array5<T>::IS &) [with T=double      ]" at line 1002 of "/home/dmacumbe/energyplus/src/EnergyPlus/DaylightingManager.      cc"

/home/dmacumbe/energyplus/third_party/ObjexxFCL/src/ObjexxFCL/Array4S.hh(3309):       warning #161: unrecognized #pragma
  #pragma clang diagnostic ignored "-Wunsequenced"
          ^
          detected during:
            instantiation of "ObjexxFCL::Array4S<T>::Array4S(T *, int64_t={long}      , const ObjexxFCL::Array4S<T>::DS &, const ObjexxFCL::Array4S<T>::DS &, const Ob      jexxFCL::Array4S<T>::DS &, const ObjexxFCL::Array4S<T>::DS &) [with T=double]" a      t line 1699 of "/home/dmacumbe/energyplus/third_party/ObjexxFCL/src/ObjexxFCL/Ar      ray5.hh"
            instantiation of "ObjexxFCL::Array4S<T> ObjexxFCL::Array5<T>::operat      or()(int, const ObjexxFCL::Array5<T>::IS &, const ObjexxFCL::Array5<T>::IS &, co      nst ObjexxFCL::Array5<T>::IS &, const ObjexxFCL::Array5<T>::IS &) [with T=double      ]" at line 1002 of "/home/dmacumbe/energyplus/src/EnergyPlus/DaylightingManager.      cc"

/home/dmacumbe/energyplus/third_party/ObjexxFCL/src/ObjexxFCL/Array4S.hh(3312):       warning #161: unrecognized #pragma
  #pragma clang diagnostic pop
          ^
          detected during:
            instantiation of "ObjexxFCL::Array4S<T>::Array4S(T *, int64_t={long}      , const ObjexxFCL::Array4S<T>::DS &, const ObjexxFCL::Array4S<T>::DS &, const Ob      jexxFCL::Array4S<T>::DS &, const ObjexxFCL::Array4S<T>::DS &) [with T=double]" a      t line 1699 of "/home/dmacumbe/energyplus/third_party/ObjexxFCL/src/ObjexxFCL/Ar      ray5.hh"
            instantiation of "ObjexxFCL::Array4S<T> ObjexxFCL::Array5<T>::operat      or()(int, const ObjexxFCL::Array5<T>::IS &, const ObjexxFCL::Array5<T>::IS &, co      nst ObjexxFCL::Array5<T>::IS &, const ObjexxFCL::Array5<T>::IS &) [with T=double      ]" at line 1002 of "/home/dmacumbe/energyplus/src/EnergyPlus/DaylightingManager.      cc"
```

I switched to building with gcc on Peregrine so this is no longer blocking me, I guess I'd say it is good for now.

**Comment by Myoldmopar** [comment]
Since we don't support Intel directly anyway, we've spent enough time on this. Merging.
